### ISSUE TITLE
Crash sharing from older devices

### ISSUE THREAD

**Issue by caarmen** [caarmen/poet-assistant#101]
```
10-19 14:23:25.245  2456  2456 E AndroidRuntime: FATAL EXCEPTION: main
10-19 14:23:25.245  2456  2456 E AndroidRuntime: Process: ca.rmen.android.poetassistant.test, PID: 2456
10-19 14:23:25.245  2456  2456 E AndroidRuntime: android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
10-19 14:23:25.245  2456  2456 E AndroidRuntime:        at android.app.ContextImpl.startActivity(ContextImpl.java:1050)
10-19 14:23:25.245  2456  2456 E AndroidRuntime:        at android.app.ContextImpl.startActivity(ContextImpl.java:1037)
10-19 14:23:25.245  2456  2456 E AndroidRuntime:        at android.content.ContextWrapper.startActivity(ContextWrapper.java:311)
10-19 14:23:25.245  2456  2456 E AndroidRuntime:        at ca.rmen.android.poetassistant.main.dictionaries.Share.share(Share.java:70)
10-19 14:23:25.245  2456  2456 E AndroidRuntime:        at ca.rmen.android.poetassistant.main.reader.ReaderViewModel.sharePoem(ReaderViewModel.java:241)
10-19 14:23:25.245  2456  2456 E AndroidRuntime:        at ca.rmen.android.poetassistant.main.reader.ReaderFragment.onOptionsItemSelected(ReaderFragment.java:144)
10-19 14:23:25.245  2456  2456 E AndroidRuntime:        at android.support.v4.app.Fragment.performOptionsItemSelected(Fragment.java:2487)
10-19 14:23:25.245  2456  2456 E AndroidRuntime:        at android.support.v4.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManager.java:3307)
10-19 14:23:25.245  2456  2456 E AndroidRuntime:        at android.support.v4.app.FragmentController.dispatchOptionsItemSelected(FragmentController.java:344)
10-19 14:23:25.245  2456  2456 E AndroidRuntime:        at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:374)
10-19 14:23:25.245  2456  2456 E AndroidRuntime:        at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:195)
10-19 14:23:25.245  2456  2456 E AndroidRuntime:        at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108)
10-19 14:23:25.245  2456  2456 E AndroidRuntime:        at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108)
10-19 14:23:25.245  2456  2456 E AndroidRuntime:        at android.support.v7.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:65)
10-19 14:23:25.245  2456  2456 E AndroidRuntime:        at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:202)
10-19 14:23:25.245  2456  2456 E AndroidRuntime:        at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:780)
10-19 14:23:25.245  2456  2456 E AndroidRuntime:        at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
10-19 14:23:25.245  2456  2456 E AndroidRuntime:        at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:171)
10-19 14:23:25.245  2456  2456 E AndroidRuntime:        at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:973)
10-19 14:23:25.245  2456  2456 E AndroidRuntime:        at android.support.v7.view.menu.MenuPopup.onItemClick(MenuPopup.java:127)
10-19 14:23:25.245  2456  2456 E AndroidRuntime:        at android.widget.AdapterView.performItemClick(AdapterView.java:299)
10-19 14:23:25.245  2456  2456 E AndroidRuntime:        at android.widget.AbsListView.performItemClick(AbsListView.java:1113)
10-19 14:23:25.245  2456  2456 E AndroidRuntime:        at android.widget.AbsListView$PerformClick.run(AbsListView.java:2911)
10-19 14:23:25.245  2456  2456 E AndroidRuntime:        at android.widget.AbsListView$3.run(AbsListView.java:3645)
10-19 14:23:25.245  2456  2456 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:733)
10-19 14:23:25.245  2456  2456 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
10-19 14:23:25.245  2456  2456 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:136)
10-19 14:23:25.245  2456  2456 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5001)
10-19 14:23:25.245  2456  2456 E AndroidRuntime:        at java.lang.reflect.Method.invokeNative(Native Method)
10-19 14:23:25.245  2456  2456 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Method.java:515)
10-19 14:23:25.245  2456  2456 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
10-19 14:23:25.245  2456  2456 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
10-19 14:23:25.245  2456  2456 E AndroidRuntime:        at dalvik.system.NativeStart.main(Native Method)
10-19 14:23:25.249   957  1315 W ActivityManager:   Force finishing activity ca.rmen.android.poetassistant.test/ca.rmen.android.poetassistant.main.MainActivity
```

**Comment by caarmen** [comment]
Fixed in 1.22.1
