### ISSUE TITLE
Exceptions preventing the app from working, on ICS

### ISSUE THREAD

**Issue by caarmen** [caarmen/poet-assistant#133]
```
12-29 06:37:16.695  1710  1710 V PoetAssistant/CoroutineThreading: java.lang.ClassCastException: android.database.sqlite.SQLiteCursor cannot be cast to java.io.Closeable
12-29 06:37:16.695  1710  1710 V PoetAssistant/CoroutineThreading: 	at ca.rmen.android.poetassistant.main.dictionaries.rt.Rhymer.getWordVariants(Rhymer.kt:44)
12-29 06:37:16.695  1710  1710 V PoetAssistant/CoroutineThreading: 	at ca.rmen.rhymer.Rhymer.getRhymingWords(Rhymer.java:52)
12-29 06:37:16.695  1710  1710 V PoetAssistant/CoroutineThreading: 	at ca.rmen.android.poetassistant.main.dictionaries.rt.RhymerLiveData.loadInBackground(RhymerLiveData.kt:92)
12-29 06:37:16.695  1710  1710 V PoetAssistant/CoroutineThreading: 	at ca.rmen.android.poetassistant.main.dictionaries.rt.RhymerLiveData.loadInBackground(RhymerLiveData.kt:38)
12-29 06:37:16.695  1710  1710 V PoetAssistant/CoroutineThreading: 	at ca.rmen.android.poetassistant.main.dictionaries.ResultListLiveData$onActive$1.invoke(ResultListLiveData.kt:35)
12-29 06:37:16.695  1710  1710 V PoetAssistant/CoroutineThreading: 	at ca.rmen.android.poetassistant.CoroutineThreading$execute$1$task$1.doResume(CoroutineThreading.kt:39)
12-29 06:37:16.695  1710  1710 V PoetAssistant/CoroutineThreading: 	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
12-29 06:37:16.695  1710  1710 V PoetAssistant/CoroutineThreading: 	at kotlinx.coroutines.experimental.DispatchTask.run(CoroutineDispatcher.kt:129)
12-29 06:37:16.695  1710  1710 V PoetAssistant/CoroutineThreading: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
12-29 06:37:16.695  1710  1710 V PoetAssistant/CoroutineThreading: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
12-29 06:37:16.695  1710  1710 V PoetAssistant/CoroutineThreading: 	at java.lang.Thread.run(Thread.java:856)
```

https://stackoverflow.com/questions/39430179/kotlin-closable-and-sqlitedatabase-on-android

**Comment by caarmen** [comment]
`Cursor` extends `Closeable` starting from jellybean.
time to change the minsdk

**Comment by anonym24** [comment]
So to support older version I have to use `.use { ... }` only from Jellybean?

            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
                cursor.use {
                    while (it.moveToNext()) {
                        videos[it.video.id] = it.video
                    }
                 }
            } else {
                while (cursor.moveToNext()) {
                    videos[cursor.video.id] = cursor.video
                }
                try {
                    cursor.close()
                } catch (e: Exception) {
                    if (BuildConfig.DEBUG) e.printStackTrace()
                }
            }

I have users running 4.0.3-4.0.4 Android and Crashlytics (or Google Console) for some of these devices reports the next exception in methods when I use `Cursor` and `SQLiteOpenHelper`

```
Caused by java.lang.ClassCastException
cannot be cast to java.io.Closeable
```
