### ISSUE TITLE
NullPointerException looking up a word

### ISSUE THREAD

**Issue by caarmen** [caarmen/poet-assistant#19]
Seen on the Play Store console, on an LGK410 for ATT, Android 6.0
```
Caused by: java.lang.NullPointerException: Attempt to read from field 'android.widget.TextView ca.rmen.android.poetassistant.databinding.FragmentResultListBinding.tvListHeader' on a null object reference
	at ca.rmen.android.poetassistant.main.dictionaries.ResultListFragment.query(ResultListFragment.java:156)
	at ca.rmen.android.poetassistant.main.dictionaries.Search.search(Search.java:93)
	at ca.rmen.android.poetassistant.main.MainActivity.onNewIntent(MainActivity.java:1157)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1213)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1225)
	at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:2563)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3103)
	... 10 more
```

**Comment by caarmen** [comment]
Got this when opening the app from the wotd notification.

```
09-18 15:47:03.241 17849 17849 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to read from field 'android.widget.TextView ca.rmen.android.poetassistant.databinding.FragmentResultListBinding.tvListHeader' on a null object reference
09-18 15:47:03.241 17849 17849 E AndroidRuntime: T>>>>>>at ca.rmen.android.poetassistant.main.dictionaries.ResultListFragment.query(ResultListFragment.java:156)
09-18 15:47:03.241 17849 17849 E AndroidRuntime: T>>>>>>at ca.rmen.android.poetassistant.main.dictionaries.Search.search(Search.java:93)
09-18 15:47:03.241 17849 17849 E AndroidRuntime: T>>>>>>at ca.rmen.android.poetassistant.main.MainActivity.onNewIntent(MainActivity.java:1157)
09-18 15:47:03.241 17849 17849 E AndroidRuntime: T>>>>>>at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1215)
09-18 15:47:03.241 17849 17849 E AndroidRuntime: T>>>>>>at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1227)
09-18 15:47:03.241 17849 17849 E AndroidRuntime: T>>>>>>at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:2582)
09-18 15:47:03.241 17849 17849 E AndroidRuntime: T>>>>>>at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3133)
09-18 15:47:03.241 17849 17849 E AndroidRuntime: T>>>>>>... 10 more
```

**Comment by caarmen** [comment]
Steps to reproduce:
* Go to settings
* change theme
* enable word of the day
* click on the wotd notification
* 💥
