### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by caarmen** [caarmen/poet-assistant#41]
```
11-02 15:56:57.271  1851  1851 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'android.widget.TextView ca.rmen.android.poetassistant.databinding.FragmentResultListBinding.tvListHeader' on a null object reference
11-02 15:56:57.271  1851  1851 E AndroidRuntime:        at ca.rmen.android.poetassistant.main.dictionaries.ResultListFragment.onSaveInstanceState(ResultListFragment.java:139)
11-02 15:56:57.271  1851  1851 E AndroidRuntime:        at android.support.v4.app.Fragment.performSaveInstanceState(Fragment.java:2251)
11-02 15:56:57.271  1851  1851 E AndroidRuntime:        at android.support.v4.app.FragmentManagerImpl.saveAllState(FragmentManager.java:19868)
11-02 15:56:57.271  1851  1851 E AndroidRuntime:        at android.support.v4.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:15134)
11-02 15:56:57.271  1851  1851 E AndroidRuntime:        at android.support.v7.app.AppCompatActivity.onSaveInstanceState(AppCompatActivity.java:515)
11-02 15:56:57.271  1851  1851 E AndroidRuntime:        at android.app.Activity.performSaveInstanceState(Activity.java:1298)
11-02 15:56:57.271  1851  1851 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1289)
11-02 15:56:57.271  1851  1851 E AndroidRuntime:        at android.app.ActivityThread.callCallActivityOnSaveInstanceState(ActivityThread.java:4088)
11-02 15:56:57.271  1851  1851 E AndroidRuntime:        at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3490)
11-02 15:56:57.271  1851  1851 E AndroidRuntime:        at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3550)
11-02 15:56:57.271  1851  1851 E AndroidRuntime:        at android.app.ActivityThread.-wrap20(ActivityThread.java)
11-02 15:56:57.271  1851  1851 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373)
11-02 15:56:57.271  1851  1851 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
11-02 15:56:57.271  1851  1851 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
11-02 15:56:57.271  1851  1851 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5417)
11-02 15:56:57.271  1851  1851 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
11-02 15:56:57.271  1851  1851 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
11-02 15:56:57.271  1851  1851 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by caarmen** [comment]
Maybe related to https://github.com/caarmen/poet-assistant/issues/19

**Comment by caarmen** [comment]
Happens with these steps: 
* open settings
* change the theme setting
* turn on the Wotd setting
      - A new Wotd notificaiton appears
* tap on the Wotd notification
