### ISSUE TITLE
Crash casting Application to PoetAssistantApplication

### ISSUE THREAD

**Issue by caarmen** [caarmen/poet-assistant#79]
```
Caused by: java.lang.ClassCastException: 
  at ca.rmen.android.poetassistant.dagger.DaggerHelper.getAppComponent(DaggerHelper.java:40)
  at ca.rmen.android.poetassistant.dagger.DaggerHelper.getMainScreenComponent(DaggerHelper.java:28)

```

Code:
```
    private static AppComponent getAppComponent(Context context) {
        return ((PoetAssistantApplication) context.getApplicationContext()).getAppComponent();
    }
```

**Comment by caarmen** [comment]
At least two variations:
``` 
Caused by: java.lang.ClassCastException: 
  at ca.rmen.android.poetassistant.dagger.DaggerHelper.getAppComponent(DaggerHelper.java:40)
  at ca.rmen.android.poetassistant.dagger.DaggerHelper.getMainScreenComponent(DaggerHelper.java:28)
  at ca.rmen.android.poetassistant.main.dictionaries.search.Search.<init>(Search.java:67)
  at ca.rmen.android.poetassistant.main.MainActivity.onCreate(MainActivity.java:117)
``` 

```
Caused by: java.lang.ClassCastException: 
  at ca.rmen.android.poetassistant.dagger.DaggerHelper.getAppComponent(DaggerHelper.java:40)
  at ca.rmen.android.poetassistant.dagger.DaggerHelper.getWotdComponent(DaggerHelper.java:36)
  at ca.rmen.android.poetassistant.wotd.WotdJobService.onCreate(WotdJobService.java:43)
  at android.app.ActivityThread.handleCreateService(ActivityThread.java:3298)
```

**Comment by caarmen** [comment]
Tried a workaround.  We'll see if this fixes the crash.
